# Generated by Django 3.2.9 on 2021-11-24 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20211124_2026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='language_name',
            new_name='name',
        ),
    ]
